name: ptype
channels:
  - conda-forge
dependencies:
  - python=3.11
  - optuna
  - pip
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - xarray
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - distributed
  - pyproj
  - cartopy
  - tqdm
  - sphinx
  - numba
  - cython
  - ruff
  - requests
  - metpy
  - herbie-data
  - cfgrib
  - numba
  - h5netcdf
  - xhistogram
  - pip:
    - pyarrow
    - keras
    - torch --index-url https://download.pytorch.org/whl/cpu
    - hagelslag
    - echo-opt
    - miles-guess
    - bridgescaler
    - zarr
    - -e .

