name: ptype
channels:
  - conda-forge
dependencies:
  - python=3.11
  - optuna
  - pip
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - xarray
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - distributed
  - pyproj
  - jupyter
  - cartopy
  - tqdm
  - sphinx
  - numba
  - cython
  - ruff
  - requests
  - metpy
  - herbie-data
  - cfgrib
  - numba
  - h5netcdf 
  - ca-certificates
  - certifi
  - openssl
  - xhistogram
  - pip:
    - pyarrow
    - keras
    - torch
    - hagelslag
    - echo-opt
    - miles-guess
    - bridgescaler
    - zarr
    - -e .

